apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: orders-service-backend-deployment
  name: orders-service-backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-service-backend
  template:
    metadata:
      labels:
        app: orders-service-backend
    spec:
      containers:
        - env:
            - name: mongo.address
              value: mongo
          image: erich852/orders-service
          name: orders-service-project
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
              protocol: TCP
          resources:
            requests:
              cpu: 1m
      restartPolicy: Always
