apiVersion: v1
kind: Service
metadata:
  labels:
    app: orders-service-backend-svc
  name: orders-service-backend-svc
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30001
  selector:
    app: orders-service-backend

